name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml pillow

      - name: Download working github-snake script
        run: |
          curl -s -L https://raw.githubusercontent.com/Ashutosh00710/github-readme-activity-graph/master/github-snake.py -o github-snake.py

      - name: Generate Snake SVG
        run: |
          python github-snake.py --username ${{ github.repository_owner }} --output output/github-contribution-grid-snake.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generate snake contribution" || echo "Nothing to commit"
          git push

